<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("blog_comment/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("blog_comment/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Blog Of Post</th>
            <th>User</th>
            <th>Title</th>
            <th>Content</th>
            <th>Deleted</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Deleted</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $blog_comment) { ?>
        <tr>
            <td><?php echo $blog_comment->id ?></td>
            <td><?php echo $blog_comment->blog_post_id ?></td>
            <td><?php echo $blog_comment->user_id ?></td>
            <td><?php echo $blog_comment->title ?></td>
            <td><?php echo $blog_comment->content ?></td>
            <td><?php echo $blog_comment->deleted ?></td>
            <td><?php echo $blog_comment->created_at ?></td>
            <td><?php echo $blog_comment->updated_at ?></td>
            <td><?php echo $blog_comment->deleted_at ?></td>
            <td><?php echo $this->tag->linkTo(array("blog_comment/edit/" . $blog_comment->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("blog_comment/delete/" . $blog_comment->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("blog_comment/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_comment/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_comment/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_comment/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
