
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("blog_tag/new", "Create blog_tag")) ?>
</div>

<?php echo $this->tag->form(array("blog_tag/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search blog_tag</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="deleted">Deleted</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("deleted", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="deleted_at">Deleted</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("deleted_at", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
