<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("blog_tag/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("blog_tag/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Deleted</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Deleted</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $blog_tag) { ?>
        <tr>
            <td><?php echo $blog_tag->id ?></td>
            <td><?php echo $blog_tag->title ?></td>
            <td><?php echo $blog_tag->deleted ?></td>
            <td><?php echo $blog_tag->created_at ?></td>
            <td><?php echo $blog_tag->updated_at ?></td>
            <td><?php echo $blog_tag->deleted_at ?></td>
            <td><?php echo $this->tag->linkTo(array("blog_tag/edit/" . $blog_tag->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("blog_tag/delete/" . $blog_tag->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("blog_tag/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_tag/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_tag/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_tag/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
