<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("blog_post/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("blog_post/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Blog Of Category</th>
            <th>Blog Of Tag Of Group</th>
            <th>Title</th>
            <th>Content</th>
            <th>Deleted</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Deleted</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $blog_post) { ?>
        <tr>
            <td><?php echo $blog_post->id ?></td>
            <td><?php echo $blog_post->user_id ?></td>
            <td><?php echo $blog_post->blog_category_id ?></td>
            <td><?php echo $blog_post->blog_tag_group_id ?></td>
            <td><?php echo $blog_post->title ?></td>
            <td><?php echo $blog_post->content ?></td>
            <td><?php echo $blog_post->deleted ?></td>
            <td><?php echo $blog_post->created_at ?></td>
            <td><?php echo $blog_post->updated_at ?></td>
            <td><?php echo $blog_post->deleted_at ?></td>
            <td><?php echo $this->tag->linkTo(array("blog_post/edit/" . $blog_post->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("blog_post/delete/" . $blog_post->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("blog_post/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_post/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_post/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("blog_post/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
